exports.getBalance = require("./simple-coin/get-balance")
exports.getAddress = require("./get-address")
exports.cidToBytes = require("./cid-to-bytes")
exports.sendCoin = require("./simple-coin/send-coin")
exports.storeAll = require("./filecoin-market-consumer/store-all")
exports.addCID = require("./deal-rewarder/add-cid")
exports.fund = require("./deal-rewarder/fund")
exports.claimBounty = require("./deal-rewarder/claim-bounty")