exports.getBalance = require("./get-balance")
exports.getAddress = require("./get-address")
exports.sendCoin = require("./send-coin")
exports.sendFil = require("./send-fil")
exports.initAddress = require("./init-address")