exports.getBalance = require("./simple-coin/get-balance")
exports.getAddress = require("./get-address")
exports.sendCoin = require("./simple-coin/send-coin")
exports.storeAll = require("./filecoin-market-consumer/store-all")
exports.addCID = require("./deal-rewarder/add-cid")
